### ISSUE TITLE
RN new arch support is not available on latest version

### ISSUE THREAD

**Issue by asafkorem** [react-native-voice/voice#574]
Hey,
We saw that there are some fixes available on master for RN new arch.
Can you please release it?

**Comment by Mridul2820** [comment]
Any other alternative for the React Native CLI?

**Comment by AM7023** [comment]
Does anyone have any good suggestions for a CLI?

**Comment by AM7023** [comment]
> I have fixed and published separately you can try it out [react-native-voice](https://www.npmjs.com/package/@dev-amirzubair/react-native-voice)

Let’s try it, and thanks for the suggestion.

**Comment by dev-amirzubair** [comment]
@dprajapati1179 you can also visit the link I have mentioned the changes:

✅ New Architecture Support - Works with Fabric and TurboModules
✅ Bridgeless Mode - Full support for React Native's Bridgeless mode
✅ React Native 0.76+ - Tested and working with the latest RN versions
✅ Fixed Android Event Emission - Events properly reach JavaScript in new architecture
✅ Fixed iOS TurboModule Registration - Proper fallback handling for iOS
✅ Clean TypeScript Types - Updated type definitions

**Comment by waleediqbal1717** [comment]
@dev-amirzubair Your solution is working on IOS but on Android its not working.
here is error: Error: Speech recognition not available

**Comment by dprajapati1179** [comment]
> when uninstalled @react-native-voice/voice it shows error like @react-native-voice/voice package is missing

Because  the name also changed so change all your import statements with new name of thee package.

**Comment by sakthinaveenm** [comment]
> > when uninstalled @react-native-voice/voice it shows error like @react-native-voice/voice package is missing
> 
> Because the name also changed so change all your import statements with new name of thee package.

PluginError: Unable to resolve a valid config plugin for @dev-amirzubair/react-native-voice.
• main export of @dev-amirzubair/react-native-voice does not appear to be a config plugin: the following error was thrown when importing /Users/kpost/Desktop/Projects/demo/node_modules/@dev-amirzubair/react-native-voice/app.plugin.js: Cannot find module '@react-native-voice/voice/package.json'

**Comment by SenerPhoenix** [comment]
Still not working. I tried everything. I'm testing on real device and Google is installed as well. startSpeech is returning null.

**Comment by dev-amirzubair** [comment]
> Still not working. I tried everything. I'm testing on real device and Google is installed as well. startSpeech is returning null.

If you previously installed the original library, please remove it first. Then install @dev-amirzubair/react-native-voice from the following link:
https://www.npmjs.com/package/@dev-amirzubair/react-native-voice
After installation, clean the build folder, rebuild the project, and try again.

**Comment by dktechprojectphuc** [comment]
> > Still not working. I tried everything. I'm testing on real device and Google is installed as well. startSpeech is returning null.
> 
> If you previously installed the original library, please remove it first. Then install @dev-amirzubair/react-native-voice from the following link: https://www.npmjs.com/package/@dev-amirzubair/react-native-voice After installation, clean the build folder, rebuild the project, and try again.

Hello. Error: Speech recognition is not available on this device. I try clean build folder, delete node_modules and have Google Search App on my phone but it's still show this message.

```jsx
 useEffect(() => {
    // Request microphone permission on Android
    const requestMicrophonePermission = async () => {
      if (Platform.OS === 'android') {
        try {
          const granted = await PermissionsAndroid.request(
            PermissionsAndroid.PERMISSIONS.RECORD_AUDIO,
            {
              title: 'Quyền Microphone',
              message:
                'App cần quyền truy cập microphone để nhận diện giọng nói',
              buttonNeutral: 'Hỏi lại sau',
              buttonNegative: 'Từ chối',
              buttonPositive: 'Đồng ý',
            },
          );
          if (granted === PermissionsAndroid.RESULTS.GRANTED) {
            console.log('Microphone permission granted');
          } else {
            console.log('Microphone permission denied');
          }
        } catch (err) {
          console.warn(err);
        }
      }
    };

    requestMicrophonePermission();

    Voice.onSpeechStart = onSpeechStart;
    Voice.onSpeechEnd = onSpeechEnd;
    Voice.onSpeechResults = onSpeechResults;
    Voice.onSpeechError = onSpeechError;

    return () => {
      Voice.destroy().then(Voice.removeAllListeners);
    };
  }, []);
```

<img width="1080" height="2400" alt="Image" src="https://github.com/user-attachments/assets/2d0d5a19-4066-4917-8048-9d9ed4c894de" />

**Comment by vuongnh1705** [comment]
> I have fixed and published separately you can try it out [react-native-voice](https://www.npmjs.com/package/@dev-amirzubair/react-native-voice)

In iOS, I get an error as soon as I call the start function, and on Android, I get an error as soon as I press stop

<img width="475" height="224" alt="Image" src="https://github.com/user-attachments/assets/54dca17e-896d-4a9b-86b7-363230e3ae63" />

<img width="484" height="456" alt="Image" src="https://github.com/user-attachments/assets/7361ee7d-8d6d-444d-a660-67462b08defd" />

**Comment by Ridwan226** [comment]
[https://github.com/adelbeke/react-native-speech-to-text/tree/main](javascript:void(0);)

my alternative is using this support RN 0.82.0

**Comment by safaiyeh** [comment]
This project has been deprecated and archived. Please migrate to [`expo-speech-recognition`](https://github.com/jamsch/expo-speech-recognition).
Thank you for your contributions! ❤️
